### ISSUE TITLE
一点不成熟的小建议

### ISSUE THREAD

**Issue by spwCoding** [ning767566973/Android-MVVM-Architecture#1]
{ withContext(Dispatchers.IO) { block() } },这句代码没必要再指定IO线程吧，直接执行block方法就可以，因为你viewModel里调用的retrofit和okhttp默认会开启子线程执后台任务，这里没必要再开启线程执行了。或者为了兼容性更好可以加一层判断

if(Thread.currentThread()==Looper.getMainLooper().thread)
      block()
 else
      withContext(Dispatchers.IO) { block() }

launchUI {
            handleException(
                { withContext(Dispatchers.IO) { block() } },
                //{ block() },
                { res ->
                    executeResponse(res) { success(it) }
                },
                {
                    if (isShowErrorMsg) {
                        defUI.toastEvent.postValue("${it.code}:${it.errMsg}")
                    }
                    error(it)
                },
                {
                    defUI.dismissDialog.call()
                    complete()
                }
            )
        }

**Comment by ning767566973** [comment]
感谢！
